zuul:
  routes:
    order-service:
      path: /order/**
      serviceId: order-service
    menu-service:
      path: /menu/**
      serviceId: menu-service
    user-service:
      path: /user/**
      serviceId: user-service